---
title: "Experience"
---

# Education

::: {.plain-list}
-   University of Sydney: Bachelor of Advanced Science, Pure Mathematics, 2000&ndash;2003
-   University of Sydney: Doctor of Philosophy, Applied Mathematics, 2004&ndash;2008
:::

# Positions

::: {.timeline}

::: {.timeline-item}
<span class="years">2026&ndash;present</span>
<span class="role">Executive Director of Natural Language Measurement, College Board</span>
:::

::: {.timeline-item}
<span class="years">2020&ndash;2026</span>
<span class="role">Principal Data Scientist, Cambium Assessment</span>
:::

::: {.timeline-item}
<span class="years">2017&ndash;2020</span>
<span class="role">Principal Mathematician, American Institutes for Research</span>
:::

::: {.timeline-item}
<span class="years">2016&ndash;2017</span>
<span class="role">Assistant Professor, The University of Maine</span>
:::

::: {.timeline-item}
<span class="years">2013&ndash;2016</span>
<span class="role">Olga-Tausky-Todd Instructor, Caltech</span>
:::

::: {.timeline-item}
<span class="years">2010&ndash;2013</span>
<span class="role">Lecturer and Research Fellow, La Trobe University</span>
:::

::: {.timeline-item}
<span class="years">2008&ndash;2010</span>
<span class="role">Postdoctoral Researcher, Melbourne University</span>
:::

:::

# Awards and Honors

::: {.plain-list}
-   National Council on Measurement in Education (NCME) &mdash; Service Award, 2026
-   Co-chair of the NCME SIGIMIE on Artificial Intelligence in Measurement and Education, 2023
-   Automated Scoring Challenge for The Nation's Report Card &mdash; Grand Prize Winner, 2021
-   American Institutes for Research &mdash; Assessment's MVP, 2018
-   ARC Discovery Project &mdash; Discrete Integrable Systems &mdash; Discovery Early Career Researcher Award, 2011&ndash;2013
-   ARC Discovery Project &mdash; The Sakai scheme &ndash; Askey table correspondence, analogues of isomonodromy and determinantal point processes, 2009&ndash;2011
-   Grant for AMSI Workshop on Nonlinear Dynamical Systems, 2012
-   Isaac Newton Institute for Mathematical Sciences, Cambridge UK, Research Scholar, 2009
:::

# Teaching

::: {.plain-list}
-   Caltech, 2015, Combinatorial Analysis
-   Caltech, 2014, Galois Theory and Representation Theory
-   Caltech, 2014, Combinatorial Analysis
-   Caltech, 2013, q-special functions with applications to integrable systems
-   Caltech, 2013, Galois Theory and Representation Theory
-   La Trobe University, 2010, Calculus and Linear Algebra
-   La Trobe University, 2010&ndash;2012, Scientific Computing
-   La Trobe University, 2012, Discrete Integrable Systems
-   Sydney University, School of Physics, 2001&ndash;2002, Scientific Computing/Scientific Visualization
-   Sydney University, School of Physics, 2003&ndash;2007, Computational Science in C
-   Sydney University, School of Mathematics, 2004&ndash;2007, Linear Algebra, Calculus, ODEs
-   University of New South Wales, Department of Mathematics, 2007, Calculus
-   La Trobe University, Department of Mathematics, 2010, Vector Calculus, Linear Algebra
:::
